import moment from 'moment-timezone';

export const allTimezones = [
  'Etc/GMT+12',
  'Pacific/Niue',
  'Pacific/Pago_Pago',
  'Pacific/Honolulu',
  'Pacific/Marquesas',
  'America/Anchorage',
  'America/Los_Angeles',
  'America/Tijuana',
  'America/Phoenix',
  'America/Chihuahua',
  'America/La_Paz',
  'America/Mazatlan',
  'America/Denver',
  'America/Guatemala',
  'America/Chicago',
  'America/Guadalajara',
  'America/Mexico_City',
  'America/Monterrey',
  'America/Regina',
  'America/Bogota',
  'America/Lima',
  'America/Quito',
  'America/New_York',
  'America/Indiana/Indianapolis',
  'America/Caracas',
  'America/Halifax',
  'America/Manaus',
  'America/Santiago',
  'America/St_Johns',
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'America/Guyana',
  'America/Godthab',
  'America/Montevideo',
  'Atlantic/South_Georgia',
  'Atlantic/Cape_Verde',
  'Atlantic/Azores',
  'Africa/Casablanca',
  'Africa/Monrovia',
  'Atlantic/Reykjavik',
  'Europe/Dublin',
  'Europe/Edinburgh',
  'Europe/Lisbon',
  'Europe/London',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Zurich',
  'Europe/Rome',
  'Europe/Stockholm',
  'Europe/Vienna',
  'Europe/Belgrade',
  'Europe/Bratislava',
  'Europe/Budapest',
  'Europe/Ljubljana',
  'Europe/Prague',
  'Europe/Brussels',
  'Europe/Copenhagen',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Sarajevo',
  'Europe/Skopje',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Africa/Lagos',
  'Asia/Amman',
  'Europe/Athens',
  'Europe/Bucharest',
  'Europe/Istanbul',
  'Asia/Beirut',
  'Africa/Cairo',
  'Africa/Harare',
  'Africa/Johannesburg',
  'Europe/Helsinki',
  'Europe/Kiev',
  'Europe/Riga',
  'Europe/Sofia',
  'Europe/Tallinn',
  'Europe/Vilnius',
  'Asia/Jerusalem',
  'Asia/Kuwait',
  'Asia/Riyadh',
  'Asia/Baghdad',
  'Europe/Moscow',
  'Europe/Moscow',
  'Europe/Volgograd',
  'Africa/Nairobi',
  'Asia/Tehran',
  'Asia/Dubai',
  'Asia/Muscat',
  'Asia/Baku',
  'Asia/Yerevan',
  'Asia/Kabul',
  'Asia/Yekaterinburg',
  'Asia/Karachi',
  'Asia/Karachi',
  'Asia/Tashkent',
  'Asia/Kolkata',
  'Asia/Kolkata',
  'Asia/Kolkata',
  'Asia/Kolkata',
  'Asia/Colombo',
  'Asia/Kathmandu',
  'Asia/Almaty',
  'Asia/Novosibirsk',
  'Asia/Dhaka',
  'Asia/Dhaka',
  'Asia/Yangon',
  'Asia/Bangkok',
  'Asia/Bangkok',
  'Asia/Jakarta',
  'Asia/Krasnoyarsk',
  'Asia/Shanghai',
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Urumqi',
  'Asia/Kuala_Lumpur',
  'Asia/Singapore',
  'Asia/Irkutsk',
  'Asia/Ulaanbaatar',
  'Australia/Perth',
  'Asia/Taipei',
  'Australia/Eucla',
  'Asia/Tokyo',
  'Asia/Tokyo',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Asia/Yakutsk',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Australia/Brisbane',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Australia/Sydney',
  'Australia/Hobart',
  'Pacific/Guam',
  'Pacific/Port_Moresby',
  'Asia/Vladivostok',
  'Australia/Lord_Howe',
  'Asia/Magadan',
  'Pacific/Guadalcanal',
  'Pacific/Noumea',
  'Pacific/Norfolk',
  'Asia/Anadyr',
  'Asia/Kamchatka',
  'Pacific/Auckland',
  'Pacific/Wellington',
  'Pacific/Fiji',
  'Pacific/Majuro',
  'Pacific/Chatham',
  'Pacific/Tongatapu',
  'Pacific/Kiritimati',
];


export const bleh = [
  {'label': '(UTC-12:00) Baker Island, Howland Island', 'value': 'Etc/GMT+12'},
  {'label': '(UTC-11:00) Niue', 'value': 'Pacific/Niue'},
  {'label': '(UTC-11:00) Samoa', 'value': 'Pacific/Pago_Pago'},
  {'label': '(UTC-10:00) Hawaii', 'value': 'Pacific/Honolulu'},
  {'label': '(UTC-09:30) Marquesas Islands', 'value': 'Pacific/Marquesas'},
  {'label': '(UTC-09:00) Alaska', 'value': 'America/Anchorage'},
  {'label': '(UTC-08:00) Pacific Time (US & Canada)', 'value': 'America/Los_Angeles'},
  {'label': '(UTC-08:00) Tijuana, Baja California', 'value': 'America/Tijuana'},
  {'label': '(UTC-07:00) Arizona', 'value': 'America/Phoenix'},
  {'label': '(UTC-07:00) Chihuahua', 'value': 'America/Chihuahua'},
  {'label': '(UTC-07:00) La Paz', 'value': 'America/La_Paz'},
  {'label': '(UTC-07:00) Mazatlan', 'value': 'America/Mazatlan'},
  {'label': '(UTC-07:00) Mountain Time (US & Canada)', 'value': 'America/Denver'},
  {'label': '(UTC-06:00) Central America', 'value': 'America/Guatemala'},
  {'label': '(UTC-06:00) Central Time (US & Canada)', 'value': 'America/Chicago'},
  {'label': '(UTC-06:00) Guadalajara', 'value': 'America/Guadalajara'},
  {'label': '(UTC-06:00) Mexico City', 'value': 'America/Mexico_City'},
  {'label': '(UTC-06:00) Monterrey', 'value': 'America/Monterrey'},
  {'label': '(UTC-06:00) Saskatchewan', 'value': 'America/Regina'},
  {'label': '(UTC-05:00) Bogota', 'value': 'America/Bogota'},
  {'label': '(UTC-05:00) Lima', 'value': 'America/Lima'},
  {'label': '(UTC-05:00) Quito', 'value': 'America/Quito'},
  {'label': '(UTC-05:00) Eastern Time (US & Canada)', 'value': 'America/New_York'},
  {'label': '(UTC-05:00) Indiana (East)', 'value': 'America/Indiana/Indianapolis'},
  {'label': '(UTC-04:00) Caracas', 'value': 'America/Caracas'},
  {'label': '(UTC-04:00) Atlantic Time (Canada)', 'value': 'America/Halifax'},
  {'label': '(UTC-04:00) Manaus', 'value': 'America/Manaus'},
  {'label': '(UTC-04:00) Santiago', 'value': 'America/Santiago'},
  {'label': '(UTC-03:30) Newfoundland', 'value': 'America/St_Johns'},
  {'label': '(UTC-03:00) Brasilia', 'value': 'America/Sao_Paulo'},
  {'label': '(UTC-03:00) Buenos Aires', 'value': 'America/Argentina/Buenos_Aires'},
  {'label': '(UTC-03:00) Georgetown', 'value': 'America/Guyana'},
  {'label': '(UTC-03:00) Greenland', 'value': 'America/Godthab'},
  {'label': '(UTC-03:00) Montevideo', 'value': 'America/Montevideo'},
  {'label': '(UTC-02:00) South Georgia & South Sandwich Islands', 'value': 'Atlantic/South_Georgia'},
  {'label': '(UTC-01:00) Cape Verde', 'value': 'Atlantic/Cape_Verde'},
  {'label': '(UTC-01:00) Azores', 'value': 'Atlantic/Azores'},
  {'label': '(UTC+00:00) Casablanca', 'value': 'Africa/Casablanca'},
  {'label': '(UTC+00:00) Monrovia', 'value': 'Africa/Monrovia'},
  {'label': '(UTC+00:00) Reykjavik', 'value': 'Atlantic/Reykjavik'},
  {'label': '(UTC+00:00) Greenwich Mean Time: Dublin', 'value': 'Europe/Dublin'},
  {'label': '(UTC+00:00) Edinburgh', 'value': 'Europe/Edinburgh'},
  {'label': '(UTC+00:00) Lisbon', 'value': 'Europe/Lisbon'},
  {'label': '(UTC+00:00) London', 'value': 'Europe/London'},
  {'label': '(UTC+01:00) Amsterdam', 'value': 'Europe/Amsterdam'},
  {'label': '(UTC+01:00) Berlin', 'value': 'Europe/Berlin'},
  {'label': '(UTC+01:00) Bern', 'value': 'Europe/Zurich'},
  {'label': '(UTC+01:00) Rome', 'value': 'Europe/Rome'},
  {'label': '(UTC+01:00) Stockholm', 'value': 'Europe/Stockholm'},
  {'label': '(UTC+01:00) Vienna', 'value': 'Europe/Vienna'},
  {'label': '(UTC+01:00) Belgrade', 'value': 'Europe/Belgrade'},
  {'label': '(UTC+01:00) Bratislava', 'value': 'Europe/Bratislava'},
  {'label': '(UTC+01:00) Budapest', 'value': 'Europe/Budapest'},
  {'label': '(UTC+01:00) Ljubljana', 'value': 'Europe/Ljubljana'},
  {'label': '(UTC+01:00) Prague', 'value': 'Europe/Prague'},
  {'label': '(UTC+01:00) Brussels', 'value': 'Europe/Brussels'},
  {'label': '(UTC+01:00) Copenhagen', 'value': 'Europe/Copenhagen'},
  {'label': '(UTC+01:00) Madrid', 'value': 'Europe/Madrid'},
  {'label': '(UTC+01:00) Paris', 'value': 'Europe/Paris'},
  {'label': '(UTC+01:00) Sarajevo', 'value': 'Europe/Sarajevo'},
  {'label': '(UTC+01:00) Skopje', 'value': 'Europe/Skopje'},
  {'label': '(UTC+01:00) Warsaw', 'value': 'Europe/Warsaw'},
  {'label': '(UTC+01:00) Zagreb', 'value': 'Europe/Zagreb'},
  {'label': '(UTC+01:00) West Central Africa', 'value': 'Africa/Lagos'},
  {'label': '(UTC+02:00) Amman', 'value': 'Asia/Amman'},
  {'label': '(UTC+02:00) Athens', 'value': 'Europe/Athens'},
  {'label': '(UTC+02:00) Bucharest', 'value': 'Europe/Bucharest'},
  {'label': '(UTC+02:00) Istanbul', 'value': 'Europe/Istanbul'},
  {'label': '(UTC+02:00) Beirut', 'value': 'Asia/Beirut'},
  {'label': '(UTC+02:00) Cairo', 'value': 'Africa/Cairo'},
  {'label': '(UTC+02:00) Harare', 'value': 'Africa/Harare'},
  {'label': '(UTC+02:00) Pretoria', 'value': 'Africa/Johannesburg'},
  {'label': '(UTC+02:00) Helsinki', 'value': 'Europe/Helsinki'},
  {'label': '(UTC+02:00) Kyiv', 'value': 'Europe/Kiev'},
  {'label': '(UTC+02:00) Riga', 'value': 'Europe/Riga'},
  {'label': '(UTC+02:00) Sofia', 'value': 'Europe/Sofia'},
  {'label': '(UTC+02:00) Tallinn', 'value': 'Europe/Tallinn'},
  {'label': '(UTC+02:00) Vilnius', 'value': 'Europe/Vilnius'},
  {'label': '(UTC+02:00) Jerusalem', 'value': 'Asia/Jerusalem'},
  {'label': '(UTC+03:00) Kuwait', 'value': 'Asia/Kuwait'},
  {'label': '(UTC+03:00) Riyadh', 'value': 'Asia/Riyadh'},
  {'label': '(UTC+03:00) Baghdad', 'value': 'Asia/Baghdad'},
  {'label': '(UTC+03:00) Moscow', 'value': 'Europe/Moscow'},
  {'label': '(UTC+03:00) St. Petersburg', 'value': 'Europe/Moscow'},
  {'label': '(UTC+03:00) Volgograd', 'value': 'Europe/Volgograd'},
  {'label': '(UTC+03:00) Nairobi', 'value': 'Africa/Nairobi'},
  {'label': '(UTC+03:30) Tehran', 'value': 'Asia/Tehran'},
  {'label': '(UTC+04:00) Abu Dhabi', 'value': 'Asia/Dubai'},
  {'label': '(UTC+04:00) Muscat', 'value': 'Asia/Muscat'},
  {'label': '(UTC+04:00) Baku', 'value': 'Asia/Baku'},
  {'label': '(UTC+04:00) Yerevan', 'value': 'Asia/Yerevan'},
  {'label': '(UTC+04:30) Kabul', 'value': 'Asia/Kabul'},
  {'label': '(UTC+05:00) Yekaterinburg', 'value': 'Asia/Yekaterinburg'},
  {'label': '(UTC+05:00) Islamabad', 'value': 'Asia/Karachi'},
  {'label': '(UTC+05:00) Karachi', 'value': 'Asia/Karachi'},
  {'label': '(UTC+05:00) Tashkent', 'value': 'Asia/Tashkent'},
  {'label': '(UTC+05:30) Chennai', 'value': 'Asia/Kolkata'},
  {'label': '(UTC+05:30) Kolkata', 'value': 'Asia/Kolkata'},
  {'label': '(UTC+05:30) Mumbai', 'value': 'Asia/Kolkata'},
  {'label': '(UTC+05:30) New Delhi', 'value': 'Asia/Kolkata'},
  {'label': '(UTC+05:30) Sri Jayawardenapura', 'value': 'Asia/Colombo'},
  {'label': '(UTC+05:45) Kathmandu', 'value': 'Asia/Kathmandu'},
  {'label': '(UTC+06:00) Almaty', 'value': 'Asia/Almaty'},
  {'label': '(UTC+06:00) Novosibirsk', 'value': 'Asia/Novosibirsk'},
  {'label': '(UTC+06:00) Astana', 'value': 'Asia/Dhaka'},
  {'label': '(UTC+06:00) Dhaka', 'value': 'Asia/Dhaka'},
  {'label': '(UTC+06:30) Yangon', 'value': 'Asia/Yangon'},
  {'label': '(UTC+07:00) Bangkok', 'value': 'Asia/Bangkok'},
  {'label': '(UTC+07:00) Hanoi', 'value': 'Asia/Bangkok'},
  {'label': '(UTC+07:00) Jakarta', 'value': 'Asia/Jakarta'},
  {'label': '(UTC+07:00) Krasnoyarsk', 'value': 'Asia/Krasnoyarsk'},
  {'label': '(UTC+08:00) Beijing', 'value': 'Asia/Shanghai'},
  {'label': '(UTC+08:00) Chongqing', 'value': 'Asia/Shanghai'},
  {'label': '(UTC+08:00) Hong Kong', 'value': 'Asia/Hong_Kong'},
  {'label': '(UTC+08:00) Urumqi', 'value': 'Asia/Urumqi'},
  {'label': '(UTC+08:00) Kuala Lumpur', 'value': 'Asia/Kuala_Lumpur'},
  {'label': '(UTC+08:00) Singapore', 'value': 'Asia/Singapore'},
  {'label': '(UTC+08:00) Irkutsk', 'value': 'Asia/Irkutsk'},
  {'label': '(UTC+08:00) Ulaanbaatar', 'value': 'Asia/Ulaanbaatar'},
  {'label': '(UTC+08:00) Perth', 'value': 'Australia/Perth'},
  {'label': '(UTC+08:00) Taipei', 'value': 'Asia/Taipei'},
  {'label': '(UTC+08:45) Eucla', 'value': 'Australia/Eucla'},
  {'label': '(UTC+09:00) Osaka', 'value': 'Asia/Tokyo'},
  {'label': '(UTC+09:00) Sapporo', 'value': 'Asia/Tokyo'},
  {'label': '(UTC+09:00) Tokyo', 'value': 'Asia/Tokyo'},
  {'label': '(UTC+09:00) Seoul', 'value': 'Asia/Seoul'},
  {'label': '(UTC+09:00) Yakutsk', 'value': 'Asia/Yakutsk'},
  {'label': '(UTC+09:30) Adelaide', 'value': 'Australia/Adelaide'},
  {'label': '(UTC+09:30) Darwin', 'value': 'Australia/Darwin'},
  {'label': '(UTC+10:00) Brisbane', 'value': 'Australia/Brisbane'},
  {'label': '(UTC+10:00) Canberra', 'value': 'Australia/Sydney'},
  {'label': '(UTC+10:00) Melbourne', 'value': 'Australia/Melbourne'},
  {'label': '(UTC+10:00) Sydney', 'value': 'Australia/Sydney'},
  {'label': '(UTC+10:00) Hobart', 'value': 'Australia/Hobart'},
  {'label': '(UTC+10:00) Guam', 'value': 'Pacific/Guam'},
  {'label': '(UTC+10:00) Port Moresby', 'value': 'Pacific/Port_Moresby'},
  {'label': '(UTC+10:00) Vladivostok', 'value': 'Asia/Vladivostok'},
  {'label': '(UTC+10:30) Lord Howe Island', 'value': 'Australia/Lord_Howe'},
  {'label': '(UTC+11:00) Magadan', 'value': 'Asia/Magadan'},
  {'label': '(UTC+11:00) Solomon Is.', 'value': 'Pacific/Guadalcanal'},
  {'label': '(UTC+11:00) New Caledonia', 'value': 'Pacific/Noumea'},
  {'label': '(UTC+11:00) Norfolk Island', 'value': 'Pacific/Norfolk'},
  {'label': '(UTC+12:00) Anadyr', 'value': 'Asia/Anadyr'},
  {'label': '(UTC+12:00) Kamchatka', 'value': 'Asia/Kamchatka'},
  {'label': '(UTC+12:00) Auckland', 'value': 'Pacific/Auckland'},
  {'label': '(UTC+12:00) Wellington', 'value': 'Pacific/Wellington'},
  {'label': '(UTC+12:00) Fiji', 'value': 'Pacific/Fiji'},
  {'label': '(UTC+12:00) Marshall Is.', 'value': 'Pacific/Majuro'},
  {'label': '(UTC+12:45) Chatham Islands', 'value': 'Pacific/Chatham'},
  {'label': '(UTC+13:00) Nuku\'alofa', 'value': 'Pacific/Tongatapu'},
  {'label': '(UTC+14:00) Kiritimati Island', 'value': 'Pacific/Kiritimati'},
];


