ALTER TABLE auth_token
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE auth_token
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE rataplanuser
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE rataplanuser
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;
