ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isstartdate;

ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isenddate;

ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isstarttime;

ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isendtime;

ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isurl;

ALTER TABLE IF EXISTS public.vote DROP COLUMN IF EXISTS isdescription;

