ALTER TABLE survey
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE questionGroup
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE question
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE checkboxGroup
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE checkbox
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE answer
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE surveyresponse
    ALTER COLUMN id TYPE BIGINT;