ALTER TABLE appointment
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE appointment
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE appointmentdecision
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE appointmentdecision
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE appointmentmember
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE appointmentmember
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE appointmentrequest
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE appointmentrequest
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE appointmentrequestconfig
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE appointmentrequestconfig
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE backenduser
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE backenduser
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;

ALTER TABLE backenduseraccess
    ADD COLUMN creationTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN lastUpdated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE backenduseraccess
    ALTER COLUMN creationTime DROP DEFAULT,
    ALTER COLUMN lastUpdated DROP DEFAULT,
    ALTER COLUMN version DROP DEFAULT;