ALTER TABLE rataplanUser
ALTER COLUMN username SET DATA TYPE VARCHAR(100);
ALTER TABLE rataplanUser
ALTER COLUMN mail SET DATA TYPE VARCHAR(200);
ALTER TABLE rataplanUser
ALTER COLUMN displayname SET DATA TYPE VARCHAR(100);